roots:
  - "P:\\JOBS"
  - "P:\\ARCHIVES\\OLD JOBS"

job_id_regex: "(?P<job>\\b\\d{3}-\\d{2}\\b)"

scan_policy:
  only_year_dirs_under_roots: true
  year_dir_regex: ".*\\b(19|20)\\d{2}\\b.*"
  year_min: 2015
  year_max: 2025

denylist_paths:
  - "P:\\$RECYCLE.BIN"
  - "P:\\System Volume Information"

pdf_text:
  enabled: true
  path_allow_tokens: ["calc", "calcs", "compress", "ame", "design", "spec"]
  max_pages: 10        # best-practice cap
  max_chars: 40000

office_text:
  enabled: false       # flip to true later if you want XLSX/DOCX/PPTX content
  include: ["xlsx","csv","docx","pptx","text"]
  max_chars: 40000
  csv_max_lines: 200
  xlsx_sheet_limit: 3
  xlsx_cells_limit: 500

detectors:
  compress:
    ext_any: [".cw7", ".xml"]
    name_tokens_any: ["compress", "codeware"]
  ametank:
    ext_any: [".mdl", ".xmt_txt"]
    name_tokens_any: ["ametank", "ame"]
  cad:
    ext_any: [".dwg", ".dxf"]
  pdf:
    ext_any: [".pdf"]
  excel:
    ext_any: [".xlsx", ".xlsm", ".xls", ".csv"]
  word:
    ext_any: [".docx", ".doc"]
  powerpoint:
    ext_any: [".pptx", ".ppt"]
  archive:
    ext_any: [".zip", ".7z", ".rar"]
# keep your existing roots for JOBS/ARCHIVES as-is
quotes_roots:
  - "P:\\QUOTES"

quotes_scan:
  year_min: 2022
  year_max: 2100   # future-proof

pdf_text:
  enabled: true
  # broaden for QUOTES so PDF body text gets indexed
  # (you can drop path_allow_tokens entirely if you want max recall)
  max_pages: 10
  max_chars: 40000

office_text:
  enabled: true
  include: ["docx","xlsx","pptx","csv","txt","md","xml","html","log"]
  xlsx_sheet_limit: 3
  xlsx_cells_limit: 400
  csv_max_lines: 200
  max_chars: 40000
